### ISSUE TITLE
Update manager is incorrectly formatting dates

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/FilterManager#112]
The update manager is incorrectly formatting dates.

**Comment by dkwiebe** [comment]
2018-06-27 20:06:35.4928 ERROR Error in line 14 position 27. An error was encountered when parsing a DateTime value in the XML.
2018-06-27 20:06:35.4937 ERROR    at System.ServiceModel.Syndication.Rss20FeedFormatter.DateFromString(String dateTimeString, XmlReader reader)
   at System.ServiceModel.Syndication.Rss20FeedFormatter.ReadItemFrom(XmlReader reader, SyndicationItem result, Uri feedBaseUri)
   at System.ServiceModel.Syndication.Rss20FeedFormatter.ReadItem(XmlReader reader, SyndicationFeed feed)
   at System.ServiceModel.Syndication.Rss20FeedFormatter.ReadItems(XmlReader reader, SyndicationFeed feed, Boolean& areAllItemsRead)
   at System.ServiceModel.Syndication.Rss20FeedFormatter.ReadXml(XmlReader reader, SyndicationFeed result)
   at System.ServiceModel.Syndication.Rss20FeedFormatter.ReadFrom(XmlReader reader)
   at System.ServiceModel.Syndication.SyndicationFeed.Load[TSyndicationFeed](XmlReader reader)
   at Citadel.Core.Windows.Util.Update.AppcastUpdater.<CheckForUpdate>d__3.MoveNext() in C:\git\Citadel-Windows\Citadel.Core.Windows\Util\Update\AppcastUpdater.cs:line 90

**Comment by dkwiebe** [comment]
@kfreezen Did you ever figure out what was causing this?

**Comment by kfreezen** [comment]
Figured it out now. The issue was that the platform names were mismatching between FilterManager and Filter-Windows.

Once I switched platform names to "winx64" and "winx86" instead of "win64" and "win32" the problem was fixed.
